#
# Implementation of Continuous Integration process for UNIX by Github actions (with extra additionals...)
#
name: "CI"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  ci-freebsd-qt5:
    name: "FreeBSD (x86_64 qt5)"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.actor, 'transifex')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and run unit tests in FreeBSD
      uses: vmactions/freebsd-vm@v1
      id: freebsd-qt5
      with:
        # Use sh shell
        usesh: true
        # When using rsync, you can define copyback: false to not copy files back from the VM in to the host.
        copyback: false
        prepare: |
          pkg install -y bash gcc g++ cmake qt5-buildtools qt5-charts qt5-concurrent qt5-core qt5-declarative qt5-gui qt5-location qt5-multimedia qt5-network qt5-opengl qt5-qmake qt5-script qt5-serialport qt5-widgets qxlsx Xvfb

        run: |
          mkdir builds
          cd builds
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=On -DENABLE_SHOWMYSKY=Off -DENABLE_QTWEBENGINE=Off "${{ github.workspace }}"
          make -j3
          Xvfb-run ctest --output-on-failure

